### ISSUE TITLE
NNN.vim throws error after renaming or deleting a file

### ISSUE THREAD

**Issue by jonwalstedt** [mcchrish/nnn.vim#41] opened 2019-02-26 10:00 UTC
**Describe the bug**
After using nnn.vim to rename or delete a file in the same buffer nnn throws an error when I try to open another file:

```
Error detected while processing function <SNR>275_callback[7]..<SNR>275_eval_temp_file[4]..<SNR>275_switch_back:
line    7:
E211: File "~/pathtofile/FileOne.txt" no longer available
Press ENTER or type command to continue
```

Expected result would be to open the next file without throwing an error.

**To Reproduce**

Steps to reproduce the behavior and with the **most minimal configuration**.
With only nnn.vim installed and additional configurations/plugins that helps reproduce the bug:

1. Open vim with the following init.vim
```
" Bootstrap Plug
let autoload_plug_path = stdpath('data') . '/site/autoload/plug.vim'
if !filereadable(autoload_plug_path)
  silent execute '!curl -fLo ' . autoload_plug_path . '  --create-dirs
      \ "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
unlet autoload_plug_path

packadd! matchit

" Plugins
call plug#begin('~/.nvim/plugged')
Plug 'mcchrish/nnn.vim'
let $NNN_USE_EDITOR=1
call plug#end()

```
2. Create a test folder with FileOne.txt and FileTwo.txt
3. Open folder with nvim ~/pathtofolder/FileOne.txt
4. Run command :NnnPicker '%:p:h'<cr>
5. Select FileOne.txt in NNN
6. Delete FileOne.txt in NNN by pressing <C-x> and y to confirm
7. Open the now selected FileTwo.txt by pressing enter
8. NNN throws the error
```
Error detected while processing function <SNR>275_callback[7]..<SNR>275_eval_temp_file[4]..<SNR>275_switch_back:
line    7:
E211: File "~/pathtofile/FileOne.txt" no longer available
Press ENTER or type command to continue
```

**Expected behavior**

I expect NNN to open FileTwo.txt in the current buffer in nvim without throwing an error

**Environment:**

- OS: macOs 10.14.3
- Terminal: iterm 3.2.7
- Shell: zsh 5.7.1
- Vim version: NVIM v0.4.0-dev
- Plugin manager: vim-plug
- Plugin version: master
- Nnn version: 2.3

**Comment by mcchrish** [comment] 2019-02-27 08:54
Could be a bug in nnn itself. Nnn probably still have the deleted file in the temp file used in picker mode. @jarun 

I can update the plugin so that it checks for existence of file before opening but I'm wondering if it's can also be done by nnn program.

**Comment by mcchrish** [comment] 2019-02-27 09:03
Nevermind, I think it's a bug in the plugin.

**Comment by banminkyoz** [comment] 2019-03-02 16:49
Hi there, thank you very much for suck awesome plugin. I just have a question so i don't want to open an issue. Please help me.

I start at `~/Document`

Then press 2 and go to `~/Document/test/src/test.js`. Press enter

NNN closed and open test.js

But when i trigger `<leader>n` again to open nnn. It's alway forgot the last path i open in 1,2,3,4. @@.

Can i config something for nnn.vim to remember path. So it's more convinient (i think @@)

One more, when i open nnn. Don't do anything and change to another workspace (i use osx). When i slice to go back to nvim. `h`, `j`, `k`, `l` just work as nnn is an text file. @@.

I'm using latest tmux and nnn.vim. latest nnn version 2.3

Thank you very much @@

**Comment by jarun** [comment] 2019-03-02 17:46
> It's alway forgot the last path i open in 1,2,3,4

Each context (1, 2, 3, 4) remembers it's own path. Can you explain a bit
more?

> when i open nnn. Don't do anything and change to another workspace (i use
osx). When i slice to go back to nvim. h, j, k, l just work as nnn is an
text file.

I am not on OS X. Can you please raise an issue for this?


Regards,

Arun

**Comment by jarun** [comment] 2019-03-02 19:18
OK, sorry. I didn't notice this was for the plugin. Please ignore my last answer.

In picker mode, `nnn` quits once you select a file. So the last instance you opened is gone.

@mcchrish Can the plugin do anything to remember the path? `nnn` supports a positional argument as path.

I am not sure I understand the second issue. Not on OS X,

**Comment by mcchrish** [comment] 2019-03-03 02:14
@jarun @banminkyoz the closes thing to that feature is using `nnoremap <leader>n :NnnPicker '%:p:h'<CR>` to open nnn in the current directory of the file in focus. But not quite what you have describe.

But I agree, the plugin can have a mechanism of remembering the last path.

@banminkyoz please open an issue with a feature request template so that #41 will not go out of topic.

>One more, when i open nnn. Don't do anything and change to another workspace (i use osx). When i slice to go back to nvim. h, j, k, l just work as nnn is an text file. @@.

You are probably in normal mode in that terminal buffer. Enter insert mode and you are focused inside the terminal buffer again.

**Comment by banminkyoz** [comment] 2019-03-03 02:22
> You are probably in normal mode in that terminal buffer. Enter insert mode and you are focused inside the terminal buffer again.

Lolll. How dumb am i. Well then this is not an issue. I'v open another issue so we can discuss about that.

**Comment by jonwalstedt** [comment] 2019-03-03 21:20
Any thoughts on the original issue that I reported, is this something that will be fixed? I would gladly try to do a fix my self but my vimscript skills are lacking :(

**Comment by mcchrish** [comment] 2019-03-03 23:51
It will be fixed, but I lack the time to do so. PR is always welcome though.
Initially, what I think is the problem is that when deleting a file that is opened as a buffer in vim, the plugin tries to switch back to that buffer and fails since it's not there anymore. Could be a only happening with split explorer feature, but needs investigate more.

**Comment by jonwalstedt** [comment] 2019-03-04 06:43
Yes that sounds lika a likely cause. I'm not using the split explorer feature (at least i don't think so), when i open a nnn.vim it will replace the current buffer and when i open a file from nnn.vim it closes nnn.vim and open the buffer in its place (i do not open it in a new split and im not using nnn.vim drawer style).

**Comment by TomBaxter** [comment] 2020-08-25 17:22
I've looked this over and not sure what the right answer is. I think there are three possibilities.

1. Don't do anything. This is a legit error with useful information. Though the trace is a bit ugly and of no use to the end-user.

2. Catch and reraise E211 without the trace. Retains the useful information and removes the clutter. This is what I did for https://github.com/mcchrish/nnn.vim/pull/76 .

3. Silence E211. I don't think that is a good idea because the user won't be notified about the file being removed out from under their open buffer.

**Closed** 2020-09-04 18:34 UTC
Labels: bug
