### ISSUE TITLE
Unexpected behavior when "NnnExplorer" is invoked via a <leader>key combination.

### ISSUE THREAD

**Issue by ShiranC** [mcchrish/nnn.vim#155] opened 2022-02-20 11:10 UTC
When NnnExplorer is invoked as a command ( ie. ":NnnExplorer" ), everything works as expected.

When NnnExplorer is invoked via a key combination
```
nnoremap <silent> <leader>x :NnnExplorer<cr>
```       
the window opens up showing the directory structure but the first 10 entries are ALREADY tagged .

Environment:

OS: macOS 10.15.7
Terminal: iterm2 3.5.0beta4
Shell: zsh 5.8.1 (x86_64-apple-darwin19.6.0)
Vim version: Vim 8.2 (2019 Dec 12, compiled Feb 11 2022 21:13:35)
Plugin manager: vim-plug
Plugin version: @[mcchrish](https://github.com/mcchrish) mcchrish released this Dec 05, 2021
· [1 commit ](https://github.com/mcchrish/nnn.vim/compare/v3.6...master)to master since this release
[v3.6](https://github.com/mcchrish/nnn.vim/tree/v3.6)
https://github.com/mcchrish/nnn.vim/commit/32d106a121eb4c88a8f4d0c6d779065b731c9fcb
Nnn version: 4.4

**Comment by mcchrish** [comment] 2022-02-25 23:01
I can't reproduce the problem. Here's my minimal vimrc https://github.com/mcchrish/dotfiles/blob/8b4317e856c35c6738d04c9eeccd392413e17001/vim/.vim/vimrc

**Comment by N-R-K** [comment] 2022-03-05 10:39
Can't reproduce either, tested on both XTerm and ST using vim v8.2.

@ShiranC The most likely situation is that you have another plugin that's interfering with the keybinding. Try to disable all other plugin and use a minimal/no vimrc and see if you still have the issue or not.

**Comment by N-R-K** [comment] 2022-03-19 09:12
Closing since we can't reproduce and no replies from OP.

**Closed by N-R-K** 2022-03-19 09:12 UTC
Labels: bug
