### ISSUE TITLE
Remap <enter> with nnn#action

### ISSUE THREAD

**Issue by johngodlee** [mcchrish/nnn.vim#92] opened 2021-05-07 19:50 UTC
**Is your feature request related to a problem? Please describe.**

I would like to remap the default behaviour of nnn.vim so that pressing `<enter>` opens the selected file in a new tab, rather than as the current buffer. 

**Describe the solution you'd like**

In fzf.vim, `<enter>` can be remapped using `fzf_action`:

```
let g:fzf_action = { 'enter': 'tab split' }
```

but the similar code in nnn.vim doesn't change the behaviour of `<enter>`:

```
let g:nnn#action = { 'enter': 'tab split' }
```

I also tried different ways of typing enter: `Enter`, `<enter>`, `<Enter>`, `<CR>`, `<cr>`, `cr`, `CR`, but none work. `<enter>` and `<Enter>` cause nnn.vim to lock up and can only be exited by first typing `Ctrl-c` than manually closing the terminal buffer.

**Comment by mcchrish** [comment] 2021-05-09 10:13
I'm not sure if it's possible. Even so, It's not a good idea. "Enter" is a common key used for some nnn features like creating new file/dir. Remapping it would lead to unexpected behavior. Check out `nnn#pick()` with a custom option for `edit` if it can fit your need.

**Comment by mizlan** [comment] 2021-05-17 15:44
For the record, using `<CR>` works for me, although this may cause a problem if certain functionalities simulate keyboard input that include the `<CR>` key.

**Comment by johngodlee** [comment] 2021-05-17 16:14
Interesting. Definitely doesn't work for me with the following: 

```
let g:nnn#action = { '<CR>': 'tab split' }
```

Anyway, unless @mcchrish wants to keep this open, I'm happy to close this issue.

**Comment by jarun** [comment] 2021-05-17 18:11
Closing this as per the comment above.

**Closed by jarun** 2021-05-17 18:11 UTC
Labels: enhancement
