### ISSUE TITLE
Floating window broken when number of elements exceeds height

### ISSUE THREAD

**Issue by jarun** [mcchrish/nnn.vim#93] opened 2021-05-09 06:46 UTC
I am seeing this with vim version 8.2.1767 and `nnn.vim` master.

I have the following in .vimrc:

```
nnoremap <leader>n :NnnPicker %:p:h<CR>

"Floating window (neovim latest and vim with patch 8.2.191)                                                
let g:nnn#layout = { 'window': { 'width': 0.9, 'height': 0.6, 'highlight':'Debug' } }
```

When the number of elements are greater than the floating window height moving the arrow down corrupts the statusbar. Looks like a height calculation issue.

![](https://i.imgur.com/XZ1Whvu.png)

**Comment by mcchrish** [comment] 2021-05-09 07:13
Seems to be a similar issue https://github.com/mcchrish/nnn.vim/issues/62. And bug seems to affect other plugins too https://github.com/voldikss/vim-floaterm/issues/171.

**Comment by jarun** [comment] 2021-05-09 07:28
I am not sure what can be done from `nnn`. Looks like the number of LINES and COLUMNS are advertised wrongly to `nnn`. I see the window broken with long filenames as well.

`nnn` gets LINES and COLS variables from the environment (set by ncurses): https://github.com/jarun/nnn/blob/eec63662724ae15561d964744be384e0952fefb7/src/nnn.c#L5769

I don't see this in `tabedit` layout.

**Comment by mcchrish** [comment] 2021-05-09 10:01
It's definitely a bug with vim. I was able to reproduce the problem a while back https://github.com/mcchrish/nnn.vim/issues/62#issuecomment-699570399 but some reported the problem still occurs even with my suggestions.

**Comment by mcchrish** [comment] 2021-05-09 10:45
Closing in favor or #62

**Closed by mcchrish** 2021-05-09 10:45 UTC
Labels: bug

**Comment by jarun** [comment] 2021-05-17 03:51
Just leaving a note for anyone having this problem - I don't see this issue with `nnn` compiled against `netbsd-curses` + `musl libc`.

Compilation procedure: https://github.com/jarun/nnn/wiki/Developer-guides#compile-with-musl-libc

**Comment by jarun** [comment] 2021-05-30 10:10
Second update 2: I have switched to `nvim` and this issue is gone.
