### ISSUE TITLE
^J for file selection not working properly

### ISSUE THREAD

**Issue by itaranto** [mcchrish/nnn.vim#83] opened 2021-02-13 02:07 UTC
**Description**

`^J` does not select multiple files when pressed continuously, it gets stuck in the first file.

**Steps to reproduce**

1. Open nvim
2. Run command `:NnnPicker`
3. Press key `^J`
4. Press key `^J` again
4. Only one file gets selected

**Expected behavior**

2 files are selected.

**Environment:**

- OS: Arch Linux
- Terminal: Alacritty
- Shell:
  Login shell: Bash 5.1.4
  Shell used inside Neovim: fish 3.1.2 (See below)
- Vim version: Neovim 0.4.4
- Plugin manager: vim-plug
- Plugin version: master (12a376646f05f71fb111892d07f84b94a47dbac5)
- nnn version: 3.5

**Additional context**
Running `nnn` inside Neovim's terminal does not reproduces the issue.
The command I use to run a terminal under Neovim is `:vsplit term://fish`.

It happens with space at well.

**Comment by jarun** [comment] 2021-02-13 02:54
nnn.vim opens nnn in picker mode. In picker mode, auto-advance is not done. You'll have to do it manually. This is to ensure users open only the selected file and not the auto-advanced one as well.

**Comment by jarun** [comment] 2021-05-16 19:52
Closing this as the behaviour works as designed in picker mode:

In picker mode the natural workflow is to pick a file using <kbd>Enter</kbd>.
Users who are accustomed to the current behaviour may inadvertently press <kbd>Enter</kbd> on the next file hovered on due to auto-advance which they didn't intend to open.

**Closed by jarun** 2021-05-16 19:52 UTC
Labels: bug
