### ISSUE TITLE
nnn.vim not loading

### ISSUE THREAD

**Issue by hkdd** [mcchrish/nnn.vim#31] opened 2019-01-01 14:21 UTC
**Describe the bug**

Loading nnn.vim via vundle
nnn version 2.1
vim version 8.1.575
(Both latest from Fedora repos)

When running :Np I see a brief flash (so fast I cannot read it) but the picker does not appear.  My vim does include terminal support (:term opens my terminal).

My terminal is urxvt and I can provide any additional details you need if you think that might be relevant.  

**To Reproduce**

My minimal vim config for testing nnn.vim:

set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'mcchrish/nnn.vim'
call vundle#end()
filetype plugin indent on

1. Open vim
2. Run command:  :Np or :NnnPicker

**Expected behavior**

nnn picker should appear

**Environment:**

- OS: Fedora 29
- Terminal urxvt
- Shell bash
- Vim version vim 8.1.575
- Plugin manager vundle
- Nnn version 2.1

**Comment by mcchrish** [comment] 2019-01-01 22:34
@hkdd please update to nnn to version *2.2*. Duplicate of #5 #11

**Closed by mcchrish** 2019-01-01 22:34 UTC
Labels: bug

**Comment by hkdd** [comment] 2019-01-01 22:37
nnn 2.2 resolved the proble, thanks, mcchrish.
