### ISSUE TITLE
Persistent nnn session for a vim session

### ISSUE THREAD

**Issue by mintelm** [mcchrish/nnn.vim#55] opened 2020-04-18 10:18 UTC
**Describe the solution you'd like**
I would love to have a persistent nnn session for my vim session -- meaning when I open nnn in vim and change directories or open a file, the next time I open nnn I want to be in the directory I changed to, but when I quit vim and start it again, the nnn session should be reset.

**Describe alternatives you've considered**
As nnn already implemented persistent sessions based on my other feature request (there's a new flag -S which automatically saves sessions and continues them on next nnn start) I could use an autocmd which deletes the session file after quitting vim, though this obviously also removes my nnn session used outside of vim.

**Comment by jarun** [comment] 2021-05-19 13:50
Marking it a duplicate of #43.

**Closed by jarun** 2021-05-19 13:50 UTC
Labels: enhancement
