### ISSUE TITLE
Command prompt crashed

### ISSUE THREAD

**Issue by sainnhe** [mcchrish/nnn.vim#39] opened 2019-02-08 03:23 UTC
**Describe the bug**

[cfb524ea5e1ecaa7c0eb0ab2fbb6675e298eb31d](https://github.com/jarun/nnn/commit/cfb524ea5e1ecaa7c0eb0ab2fbb6675e298eb31d) in master branch changed ^S to ^P to show the command prompt. And after I type ^P and execute a command, nnn.vim crashed.

**To Reproduce**

**most minimal configuration**:

```vim
if has('nvim')
    set runtimepath^=~/.vim runtimepath+=~/.vim/after
    let &packpath = &runtimepath
endif
call plug#begin('~/.cache/vim/plugins')
Plug 'mcchrish/nnn.vim'
call plug#end()
```
0. Compile and install nnn from master branch.
1. Open vim (or nvim)
2. Run command `:NnnPicker`
3. Press key `^P`, type `ls`

**Expected behavior**

After I execute `ls`, nnn.vim should continue to work.

**Screenshots**

![peek 2019-02-08 11-17](https://user-images.githubusercontent.com/37491630/52457165-7420bc00-2b93-11e9-85b6-74e9c322e5a0.gif)

**Environment:**

- OS: Arch Linux
- Terminal: GNOME Terminal 3.30.2 using VTE 0.54.3 +GNUTLS
- Shell: zsh 5.7.1 (x86_64-pc-linux-gnu)
- Vim version: neovim 0.3.4
- Plugin manager: vim-plug
- Plugin version: master
- Nnn version: 2.2 (compile from master branch)

**Additional context**

none.

**Comment by mcchrish** [comment] 2019-02-10 03:40
I'm able to replicate it. It doesn't seem to work with non-login shells?

I'm using iTerm in macOS and another way to replicate the issue is passing `nnn` as command, as I assume it runs as a non-login shell. My knowledge on shell environment behaviors is currently limited so I might not able to help.
<img width="535" alt="screen shot 2019-02-10 at 11 25 55 am" src="https://user-images.githubusercontent.com/7200153/52529164-3739fe00-2d28-11e9-86a2-a44f49942fd4.png">

cc @jarun

**Comment by jarun** [comment] 2019-02-10 03:43
@sainnhe are you saying `^S` used to work but `^P` has the issue?

**Comment by jarun** [comment] 2019-02-10 03:48
OK, I see the UI breaks.

**Comment by jarun** [comment] 2019-02-10 04:29
Please check if the issue is fixed with `nnn` master.

**Closed** 2019-02-10 04:29 UTC
Labels: bug, help wanted

**Comment by mcchrish** [comment] 2019-02-10 04:40
@jarun tested and works! 👍

**Comment by jarun** [comment] 2019-02-10 04:44
Awesome! Now we are using the stock prompt instead of the libreadline one when `nnn` is started in file picker mode.

**Comment by sainnhe** [comment] 2019-02-10 06:31
@jarun Thanks for your work!!

**Comment by jarun** [comment] 2019-02-10 06:34
My pleasure!
